spring:
  application:
    name: ms-manajemen-talenta
  data:
    mongodb:
      uri: mongodb+srv://root:12345@manajemen-talenta.e35gcuo.mongodb.net/manajemen-talenta?authsource=admin


server:
  port: 8080
